"""make count_in and count_out nullable

Revision ID: f57b3754ca28
Revises:
Create Date: 2026-08-11 21:08:52.313038

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f57b3754ca28"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("counts", schema=None) as batch_op:
        batch_op.alter_column("count_in", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("count_out", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("counts", schema=None) as batch_op:
        batch_op.alter_column("count_out", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("count_in", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
